import { Zap, Crown, Sparkles } from 'lucide-react';

export const PLAN_CONFIG = {
    free: {
        label: 'Standard',
        icon: Zap,
        bg: 'bg-stone-100',
        border: 'border-stone-200',
        text: 'text-stone-600',
        iconColor: 'text-stone-400',
        hoverBg: 'hover:bg-stone-200/80',
    },
    premium: {
        label: 'Premium',
        icon: Crown,
        bg: 'bg-gradient-to-r from-amber-50 to-orange-50',
        border: 'border-amber-200/60',
        text: 'text-amber-800',
        iconColor: 'text-amber-500',
        hoverBg: 'hover:from-amber-100/80 hover:to-orange-100/80',
    },
    super_premium: {
        label: 'Elite',
        icon: Sparkles,
        bg: 'bg-gradient-to-r from-violet-50 to-indigo-50',
        border: 'border-violet-200/60',
        text: 'text-violet-800',
        iconColor: 'text-violet-500',
        hoverBg: 'hover:from-violet-100/80 hover:to-indigo-100/80',
    },
};

export const PLANS = [
    {
        id: 'free',
        name: 'Standard',
        price: 'Free',
        period: '',
        description: 'Start selling your craft to the world.',
        icon: Zap,
        limit: 3,
        color: 'stone',
        gradient: 'from-stone-500 to-stone-600',
        lightBg: 'bg-stone-50',
        lightBorder: 'border-stone-200',
        lightText: 'text-stone-700',
        features: [
            'Up to 3 Active Products',
            'Core Seller Workspace',
            'Basic Analytics Dashboard',
        ],
    },
    {
        id: 'premium',
        name: 'Premium',
        price: '₱199',
        period: '/ mo',
        description: 'Grow your artisan business with stronger operational tools.',
        icon: Crown,
        limit: 10,
        color: 'amber',
        gradient: 'from-amber-500 to-orange-500',
        lightBg: 'bg-amber-50',
        lightBorder: 'border-amber-200',
        lightText: 'text-amber-700',
        recommended: true,
        features: [
            'Up to 10 Active Products',
            'Premium Badge (Crown Icon)',
            'Analytics Report Export',
            'Module Customization',
        ],
    },
    {
        id: 'super_premium',
        name: 'Elite',
        price: '₱399',
        period: '/ mo',
        description: 'Unlock the full seller suite and sponsored placements.',
        icon: Sparkles,
        limit: 50,
        color: 'violet',
        gradient: 'from-violet-500 to-indigo-500',
        lightBg: 'bg-violet-50',
        lightBorder: 'border-violet-200',
        lightText: 'text-violet-700',
        features: [
            'Up to 50 Active Products',
            'Elite Badge',
            '5 Sponsorship Credits Every 30 Days',
            'All Seller Modules Unlocked',
            'Sponsored Homepage and Catalog Placement',
        ],
    },
];
