const RAW_CAVITE_BARANGAYS = {
    // Cities
    "Bacoor City": ["Alima", "Aniban I", "Aniban II", "Aniban III", "Aniban IV", "Aniban V", "Banalo", "Bayanan", "Camposanto", "Daang Bukid", "Digman", "Dulong Bayan", "Habay I", "Habay II", "Kaingin", "Ligas I", "Ligas II", "Ligas III", "Mabolo I", "Mabolo II", "Mabolo III", "Maliksi I", "Maliksi II", "Maliksi III", "Mambog I", "Mambog II", "Mambog III", "Mambog IV", "Mambog V", "Molino I", "Molino II", "Molino III", "Molino IV", "Molino V", "Molino VI", "Molino VII", "Niog I", "Niog II", "Niog III", "P.F. Espiritu I", "P.F. Espiritu II", "P.F. Espiritu III", "P.F. Espiritu IV", "P.F. Espiritu V", "P.F. Espiritu VI", "P.F. Espiritu VII", "P.F. Espiritu VIII", "Panapaan I", "Panapaan II", "Panapaan III", "Panapaan IV", "Panapaan V", "Panapaan VI", "Panapaan VII", "Panapaan VIII", "Queens Row Central", "Queens Row East", "Queens Row West", "Real I", "Real II", "Salinas I", "Salinas II", "Salinas III", "Salinas IV", "San Nicolas I", "San Nicolas II", "San Nicolas III", "Sineguelasan", "Tabing Dagat", "Talaba I", "Talaba II", "Talaba III", "Talaba IV", "Talaba V", "Talaba VI", "Talaba VII", "Zapote I", "Zapote II", "Zapote III", "Zapote IV", "Zapote V"],
    "Cavite City": ["Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5", "Barangay 6", "Barangay 7", "Barangay 8", "Barangay 9", "Barangay 10", "Barangay 10-A", "Barangay 10-B", "Barangay 11", "Barangay 12", "Barangay 13", "Barangay 14", "Barangay 15", "Barangay 16", "Barangay 17", "Barangay 18", "Barangay 19", "Barangay 20", "Barangay 21", "Barangay 22", "Barangay 22-A", "Barangay 23", "Barangay 24", "Barangay 25", "Barangay 26", "Barangay 27", "Barangay 28", "Barangay 29", "Barangay 29-A", "Barangay 30", "Barangay 31", "Barangay 32", "Barangay 33", "Barangay 34", "Barangay 35", "Barangay 36", "Barangay 36-A", "Barangay 37", "Barangay 38", "Barangay 38-A", "Barangay 39", "Barangay 40", "Barangay 41", "Barangay 42", "Barangay 42-A", "Barangay 42-B", "Barangay 42-C", "Barangay 43", "Barangay 44", "Barangay 45", "Barangay 46", "Barangay 47", "Barangay 48", "Barangay 49", "Barangay 50", "Barangay 51", "Barangay 52", "Barangay 53", "Barangay 54", "Barangay 55", "Barangay 56", "Barangay 57", "Barangay 58", "Barangay 59", "Barangay 60", "Barangay 61", "Barangay 62"],
    "Dasmariñas City": ["Burol I", "Burol II", "Burol III", "Burol Main", "Datu Esmael", "Emmanuel Bergado I", "Emmanuel Bergado II", "Fatima I", "Fatima II", "Fatima III", "Langkaan I", "Langkaan II", "Luzviminda I", "Luzviminda II", "Paliparan I", "Paliparan II", "Paliparan III", "Sabang", "Salawag", "Salitran I", "Salitran II", "Salitran III", "Salitran IV", "Salitran V", "Salitran VI", "Sampaloc I", "Sampaloc II", "Sampaloc III", "Sampaloc IV", "Sampaloc V", "San Agustin I", "San Agustin II", "San Agustin III", "San Andres I", "San Andres II", "San Dionisio", "San Esteban", "San Francisco", "San Jose", "San Juan", "San Lorenzo Ruiz I", "San Lorenzo Ruiz II", "San Luis I", "San Luis II", "San Manuel I", "San Manuel II", "San Miguel I", "San Miguel II", "San Nicolas I", "San Nicolas II", "San Roque", "San Simon", "Santa Cruz I", "Santa Cruz II", "Santa Fe", "Santa Lucia", "Santa Maria", "Santo Cristo", "Santo Niño I", "Santo Niño II", "Victoria Reyes", "Zone I", "Zone I-A", "Zone II", "Zone III", "Zone IV"],
    "General Trias City": ["Alingaro", "Arnaldo Pob.", "Bacao I", "Bacao II", "Bagumbayan Pob.", "Biclatan", "Buenavista I", "Buenavista II", "Buenavista III", "Corregidor Pob.", "Dulong Bayan Pob.", "Gov. Ferrer Pob.", "Javalera", "Manggahan", "Navarro", "Ninety Kawit", "Panungyanan", "Pasong Camachile I", "Pasong Camachile II", "Pasong Kawayan I", "Pasong Kawayan II", "Pinagtipunan", "Prinza Pob.", "Sampalucan Pob.", "San Francisco", "San Gabriel Pob.", "San Juan I", "San Juan II", "Santa Clara", "Santiago Pob.", "Tapia", "Tejero", "Vibora Pob."],
    "Imus City": ["Alapan I-A", "Alapan I-B", "Alapan I-C", "Alapan II-A", "Alapan II-B", "Anabu I-A", "Anabu I-B", "Anabu I-C", "Anabu I-D", "Anabu I-E", "Anabu I-F", "Anabu I-G", "Anabu II-A", "Anabu II-B", "Anabu II-C", "Anabu II-D", "Anabu II-E", "Anabu II-F", "Bagong Silang", "Bayan Luma I", "Bayan Luma II", "Bayan Luma III", "Bayan Luma IV", "Bayan Luma V", "Bayan Luma VI", "Bayan Luma VII", "Bayan Luma VIII", "Bayan Luma IX", "Buhay na Tubig", "Bucandala I", "Bucandala II", "Bucandala III", "Bucandala IV", "Bucandala V", "Carsadang Bago I", "Carsadang Bago II", "Magdalo", "Maharlika", "Malagasang I-A", "Malagasang I-B", "Malagasang I-C", "Malagasang I-D", "Malagasang I-E", "Malagasang I-F", "Malagasang I-G", "Malagasang II-A", "Malagasang II-B", "Malagasang II-C", "Malagasang II-D", "Malagasang II-E", "Malagasang II-F", "Malagasang II-G", "Mariano Espeleta I", "Mariano Espeleta II", "Mariano Espeleta III", "Medicion I-A", "Medicion I-B", "Medicion I-C", "Medicion I-D", "Medicion II-A", "Medicion II-B", "Medicion II-C", "Medicion II-D", "Medicion II-E", "Medicion II-F", "Palico I", "Palico II", "Palico III", "Palico IV", "Pasong Buaya I", "Pasong Buaya II", "Pinagbuklod", "Poblacion I-A", "Poblacion I-B", "Poblacion I-C", "Poblacion II-A", "Poblacion II-B", "Poblacion III-A", "Poblacion III-B", "Poblacion IV-A", "Poblacion IV-B", "Poblacion IV-C", "Poblacion IV-D", "Tanzang Luma I", "Tanzang Luma II", "Tanzang Luma III", "Tanzang Luma IV", "Tanzang Luma V", "Tanzang Luma VI", "Toclong I-A", "Toclong I-B", "Toclong I-C", "Toclong II-A", "Toclong II-B"],
    "Tagaytay City": ["Asisan", "Bagong Tubig", "Calabuso", "Dapdap East", "Dapdap West", "Francisco", "Guinhawa North", "Guinhawa South", "Iruhin Central", "Iruhin East", "Iruhin South", "Iruhin West", "Kaybagal Central", "Kaybagal North", "Kaybagal South", "Mag-Asawang Ilat", "Maharlika East", "Maharlika West", "Maitim II Central", "Maitim II East", "Maitim II West", "Mendez Crossing East", "Mendez Crossing West", "Neogan", "Patutong Malaki North", "Patutong Malaki South", "Sambong", "San Jose", "Silang Junction North", "Silang Junction South", "Sungay East", "Sungay West", "Tolentino East", "Tolentino West", "Zambal"],
    "Trece Martires City": ["Aguado", "Cabezas", "Cabuco", "Conchu", "De Ocampo", "Gregorio", "Inocencio", "Lapidario", "Lallana", "Luciano", "Osorio", "Perez", "San Agustin"],
    // Municipalities
    "Alfonso": ["Amuyong", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Barangay V", "Bilog", "Buck Estate", "Esperanza Ibaba", "Esperanza Ilaya", "Kaysuyo", "Luksuhin Ibaba", "Luksuhin Ilaya", "Mangas I", "Mangas II", "Marahan I", "Marahan II", "Matagbak I", "Matagbak II", "Pajo", "Palumlum", "Kaytambog", "Kaytapos", "Upli", "Sikat", "Sinaliw Malaki", "Sinaliw Maliit", "Taywanak Ibaba", "Taywanak Ilaya", "Upli"],
    "Amadeo": ["Banaybanay", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Barangay V", "Barangay VI", "Barangay VII", "Barangay VIII", "Bucal", "Buho", "Dagatan", "Halang", "Laging Handa", "Maymangga", "Minantok East", "Minantok West", "Pangil", "Salaban", "Talon", "Tamacan"],
    "Carmona": ["Bancal", "Cabilang Baybay", "Lantic", "Mabuhay", "Maduya", "Milagrosa"],
    "Indang": ["Agus-os", "Alulod", "Banaba Cerca", "Banaba Lejos", "Bancod", "Buna Cerca", "Buna Lejos I", "Buna Lejos II", "Calumpang Cerca", "Calumpang Lejos I", "Calumpang Lejos II", "Carasuchi", "Daine I", "Daine II", "Guyam Malaki", "Guyam Munti", "Harasan", "Kayquit I", "Kayquit II", "Kayquit III", "Kaytapos", "Limbon", "Lumampong Balagbag", "Lumampong Halayhay", "Mahabang Kahoy Cerca", "Mahabang Kahoy Lejos", "Mataas na Lupa", "Pulo", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Tambo Balagbag", "Tambo Ilaya", "Tambo Kulit", "Tambo Malaki", "Poblacion"],
    "Kawit": ["Balsahan-Bisita", "Batong Dalig", "Binakayan-Aplaya", "Binakayan-Kanluran", "Gahak", "Kaingen", "Marulas", "Panamitan", "Poblacion", "Pulvorista", "Samala-Marquez", "San Sebastian", "Santa Isabel", "Tabon I", "Tabon II", "Tabon III", "Toclong", "Tramo-Bantayan", "Wakas I", "Wakas II"],
    "Magallanes": ["Baliwag", "Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5", "Barangay 6", "Barangay 7", "Bendita I", "Bendita II", "Caluangan", "Pacheco", "Ramirez", "San Agustin"],
    "Maragondon": ["Bucal I", "Bucal II", "Bucal III-A", "Bucal III-B", "Bucal IV-A", "Bucal IV-B", "Caingin Pob.", "Garita I-A", "Garita I-B", "Layong Mabilog", "Mabato", "Pantihan I", "Pantihan II", "Pantihan III", "Pantihan IV", "Patungan", "Pinagsanhan I-A", "Pinagsanhan I-B", "Poblacion I-A", "Poblacion I-B", "Poblacion II-A", "Poblacion II-B", "San Miguel I-A", "San Miguel I-B", "Talipusngo", "Tulay Kanluran", "Tulay Silangan"],
    "Mendez": ["Anuling Cerca I", "Anuling Cerca II", "Anuling Lejos I", "Anuling Lejos II", "Ayungon", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Galicia I", "Galicia II", "Galicia III", "Panungyan I", "Panungyan II", "Palocpoc I", "Palocpoc II"],
    "Naic": ["Bagong Karsada", "Balsahan", "Bancaan", "Bucana Malaki", "Bucana Sasahan", "Calubcob I", "Calubcob II", "Capt. C. Nazareno", "Gomez-Zamora", "Halang", "Humbac", "Ibayo Estacion", "Ibayo Silangan", "Kanluran", "Labac", "Latoria", "Mabolo", "Makina", "Malainen Bago", "Malainen Luma", "Molino", "Munting Mapino", "Palangue I", "Palangue II", "Palangue III", "Poblacion I", "Poblacion II", "Poblacion III", "Poblacion IV", "Sabang", "San Roque", "Santulan", "Sapa", "Timalan Balsahan", "Timalan Concepcion"],
    "Noveleta": ["Magdiwang", "Poblacion", "Salcedo I", "Salcedo II", "San Antonio I", "San Antonio II", "San Jose I", "San Jose II", "San Juan I", "San Juan II", "San Rafael I", "San Rafael II", "San Rafael III", "San Rafael IV", "Santa Rosa I", "Santa Rosa II"],
    "Rosario": ["Bagbag I", "Bagbag II", "Kanluran", "Ligtong I", "Ligtong II", "Ligtong III", "Ligtong IV", "Muzon I", "Muzon II", "Poblacion", "Sapa I", "Sapa II", "Sapa III", "Sapa IV", "Silangan I", "Silangan II", "Wawa I", "Wawa II", "Wawa III"],
    "Silang": ["Acacia", "Adlas", "Anahaw I", "Anahaw II", "Balite I", "Balite II", "Batas", "Biga I", "Biga II", "Biluso", "Bucal", "Buho", "Bulihan", "Cabangaan", "Carmen", "Hoyo", "Hukay", "Iba", "Inchican", "Ipil I", "Ipil II", "Kalubkob", "Kaong", "Lalaan I", "Lalaan II", "Litlit", "Lucsuhin", "Lumil", "Magallanes", "Malabag", "Mataas na Burol", "Munting Ilog", "Narra I", "Narra II", "Narra III", "Paligawan", "Pasong Langka", "Pooc I", "Pooc II", "Poblacion I", "Poblacion II", "Poblacion III", "Poblacion IV", "Poblacion V", "Pulong Bunga", "Pulong Saging", "Puting Kahoy", "Sabutan", "San Miguel I", "San Miguel II", "San Vicente I", "San Vicente II", "Santol", "Toledo", "Tubuan I", "Tubuan II", "Tubuan III", "Ulat", "Yakal"],
    "Tanza": ["Amaya I", "Amaya II", "Amaya III", "Amaya IV", "Amaya V", "Amaya VI", "Amaya VII", "Bagtas", "Biga", "Biwas", "Bucal", "Bunga", "Calibuyo", "Capipisa", "Daang Amaya I", "Daang Amaya II", "Daang Amaya III", "Halayhay", "Julugan I", "Julugan II", "Julugan III", "Julugan IV", "Julugan V", "Julugan VI", "Julugan VII", "Julugan VIII", "Mulawin", "Navotas", "Punta I", "Punta II", "Sahud Ulan", "Sanja Mayor", "Santol", "Tanauan", "Tres Cruses"],
    "Ternate": ["Bucana", "De Ocampo", "Poblacion I", "Poblacion II", "Poblacion III", "San Jose", "San Juan I", "San Juan II", "Sapang I", "Sapang II"]
}

export const normalizeCaviteAddressText = (value = '') =>
    String(value)
        .replace(/Ã±/g, 'n')
        .replace(/Ã‘/g, 'N')
        .replace(/ñ/g, 'n')
        .replace(/Ñ/g, 'N')
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/\s+/g, ' ')
        .trim();

export const CAVITE_REGION = 'Cavite';

export const CAVITE_BARANGAYS = Object.fromEntries(
    Object.entries(RAW_CAVITE_BARANGAYS).map(([city, barangays]) => [
        normalizeCaviteAddressText(city),
        (barangays || []).map((barangay) => normalizeCaviteAddressText(barangay)),
    ]),
);

export const CAVITE_CITY_OPTIONS = Object.keys(CAVITE_BARANGAYS);

export const getCaviteBarangaysForCity = (city = '') =>
    CAVITE_BARANGAYS[normalizeCaviteAddressText(city)] || [];
